baseurl = "https://lorenzo.cameroni.eu/"
title = "Lorenzo Cameroni"

theme = "hugo-coder"

languagecode = "it"
defaultcontentlanguage = "it"

paginate = 20
canonifyurls = true

#see https://xyproto.github.io/splash/docs/ e https://xyproto.github.io/splash/docs/all.html
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

# googleAnalytics = "UA-123-45"
enableRobotsTXT = true
# enableGitInfo = true


[params]
    author = "Lorenzo Cameroni"
    description = "Sito personale di Lorenzo Cameroni"
    keywords = "blog,sviluppatore,personale"
    info = "Sviluppatore, matematico"
    avatarurl = "images/lorenzo.jpg"
    #gravatar = "john.doe@example.com"
    # footercontent = "Inserisci del testo qui."

    dateformat = "2/1/2006" # era "January 2, 2006" ma non funzionano i mesi in italiano

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/came88/sito-hugo/tree"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []
    custom_scss = [ "scss/custom.scss" ]

    # Custom JS
    custom_js = [ "js/codeblock.js" ]

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"
    
# # If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "example.com"
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/came88"
    target = "_blank"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/came88"
#    target = "_blank"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/LorenzoCameroni"
    target = "_blank"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/lorenzocameroni"
    target = "_blank"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/lorenzo.cameroni/"
    target = "_blank"
# [[params.social]]
#     name = "Facebook"
#     icon = "fab fa-facebook"
#     weight = 6
#     url = "https://www.facebook.com/lorenzo.cameroni/"
#    target = "_blank"
# [[params.social]]
#     name = "Medium"
#     icon = "fab fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"
#    target = "_blank"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "blog/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
    target = "_blank"


[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"


[languages]
    [languages.it]
        languagename = "Italiano"
        # title = "Lorenzo Cameroni"

        [languages.it.menu]

            [[languages.it.menu.main]]
            name = "Chi sono"
            weight = 1
            url = "chi-sono/"

            [[languages.it.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"

            # [[languages.it.menu.main]]
            # name = "Progetti"
            # weight = 3
            # url = "progetti/"

            [[languages.it.menu.main]]
            name = "Contatti"
            weight = 5
            url = "contatti/"

    [languages.en]
        languagename = "English"

        [languages.en.params]
            author = "Lorenzo Cameroni"
            description = "Lorenzo Cameroni's personal website"
            keywords = "blog,developer,personal"
            info = "Developer, matematician"
            # footercontent = "Enter a text here."
            dateformat = "January 2, 2006"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About me"
            weight = 1
            url = "about-me/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact-me/"
